services:
  terminologue:
    build:
      context: .
      dockerfile: Dockerfile
    security_opt:
      - seccomp:unconfined
    container_name: terminologue
    ports:
      - "3380:80"
    volumes:
      - /volume1/docker/terminologue/data:/app/data
    restart: unless-stopped
